### ISSUE TITLE
Volume addition

### ISSUE THREAD

**Issue by romdim** [ad2games/docker-rails#2]
Hello there. Love your image!
I know you mention that it is intended for production use but I would really like to use it in development as well. The bad thing is that i've tried but couldn't make it to copy the folder I'm working on at the host to the container whenever I change something.
Actually, through a docker-compose.yml I've added a volume - .:/myapp but this isn't the working folder.
Whenever I change it to use -.:/home/app/webapp/ puma just won't start.
Do you have any ideas why this is happening?
Thank you very much in advance!

**Comment by dziemba** [comment]
Hey, sorry for the late answer, I'm glad you like our project!

As already mentioned, this image is intended for production use. There are ONBUILD commands that add your app code and install gems / compile assets. Just mounting a volume into the container instead of creating a new image containing the app code is not supported. In theory it could work, but I have never tried it. It would also mean that the gems of your local machine are used. For native extensions, this might cause a lot of trouble. Since there are better ways to run rails apps in development, I probably won't spend any time supporting this setup. Feel free to play around, though. If you come up with a good solution, I'd be happy to add it!

You can of course use the regular way to create you app image and run it locally in development mode (i.e. by creating a new image instead of mounting a volume). See the _Quick Example_ section of the README on how to do that.

A good idea for a development environment might be either just running everything locally on your machine or using docker-compose with other base images. The [ruby docker image](https://hub.docker.com/_/ruby/) might be a good start, especially the alpine versions are really nice. You can then run a separate container for each service (puma, sidekiq, clockwork) using docker-compose. 

I hope this helps, let me know how it turns out ;)

**Comment by benbonnet** [comment]
@dziemba somehow related to his question, wondering about the workflow

How do you move your apps from dev to prod (using this repo then) ? Simple copy paste of your dev codebase to this dockerized setup ?

**Comment by hwartig** [comment]
Development happens without involving docker. We then use [ad2games/docker-deploy](https://github.com/ad2games/docker-deploy) to build the docker container on our CI servers.

**Comment by dziemba** [comment]
Right. The basic idea is that each project has a `Dockerfile` that contains:

```
FROM ad2games/docker-rails:latest
```

(as described in the [README](../blob/master/README.md))

We then build a docker container (the ONBUILD hooks copy the app code into the container), push it to docker-hub and deploy that to EC2.

**Comment by benbonnet** [comment]
Hey thx for your replies; as I'm getting into using docker it is cool to understand ho people use it

**Comment by romdim** [comment]
Hey again @dziemba !

I have been using docker-compose with other base images after all for the local dev env. I sure wish I could use yours both in local and prod environment though. It would be really helpful.. :)

But nevermind, the outcome is pretty much the same in the end.

Cheers and keep up the good work!
