### ISSUE TITLE
Unknown MySQL server host 'noop' 

### ISSUE THREAD

**Issue by drummerroma** [ad2games/docker-rails#8]
In a new project I get this error and cannot find any reason. 

```
Step 1/1 : FROM ad2games/docker-rails:latest
# Executing 5 build triggers...
Step 1/1 : COPY Gemfile Gemfile.lock /home/app/webapp/
 ---> Using cache
Step 1/1 : COPY vendor/ /home/app/webapp/vendor/
 ---> Using cache
Step 1/1 : RUN chown -R app:app Gemfile Gemfile.lock vendor/ &&   chpst -u app bundle install --deployment --jobs 4 --without development test &&   find vendor/bundle -name *.gem -delete
 ---> Using cache
Step 1/1 : COPY . /home/app/webapp/
Step 1/1 : RUN mkdir -p db public/assets log tmp vendor &&   chown -R app:app app db public log tmp vendor && chpst -u app /opt/rails-assets.sh
 ---> Running in f3820f857ac3
/home/app/webapp/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0
Could not find gem 'pg'.
/home/app/webapp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5
WARNING: Skipping key "SECRET_KEY_BASE". Already set in ENV.
rake aborted!
**Mysql2::Error: Unknown MySQL server host 'noop' (25)**
/home/app/webapp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:89:in `connect'
/home/app/webapp/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:89:in `initialize'
/home/app/webapp/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
```

**Comment by drummerroma** [comment]
Could find the problem. 
`filter (:lists), lable:'Liste', as: :select, collection: List.all.pluck(:description, :id)`
This line in Active Admin makes a database connection in the rake assets:precompile task. I have no idea why, but seems an ActiveAdmin particularity. 
Using the AA standard filters (filter :lists) solves the problem.

Maybe you could find a better way in your rails-assets.sh, because 
`export DATABASE_URL="mysql2://noop"`
does not solve noop connections.

**Comment by dziemba** [comment]
Thanks for investigating this further. Yes, it looks like you're accessing the DB when the rails environment is loaded. That's usually not a good idea in general. When using `docker-rails` this must not happen, because obviously we don't want to connect to a real database when building the docker image.

For your example:
```
filter (:lists), lable:'Liste', as: :select, collection: List.all.pluck(:description, :id)
```

it looks like you're loading the content of the `lists` table once when loading the activeadmin class file.

Try changing it to this:

```
filter (:lists), lable:'Liste', as: :select, collection: proc { List.all.pluck(:description, :id) }
```
as described in http://activeadmin.info/docs/3-index-pages.html (Index Filters)

Please let me know if this fixed your problem.

**Comment by drummerroma** [comment]
Great, this worked!
